app.name=spark-enterprise-offline-warehouse-demo

demo.mysql.host=bigdata
demo.mysql.port=3306
demo.mysql.database=spark_offline_demo
demo.mysql.username=root
demo.mysql.password=Wzq19940920..
demo.mysql.serverTimezone=Asia/Shanghai

demo.hdfs.basePath=hdfs://bigdata:9000/warehouse/spark_offline_demo
demo.local.basePath=file:///opt/module/spark-enterprise-offline-warehouse-demo/.local-warehouse
demo.runMode=cluster
demo.bizDate=2026-05-14

spark.sql.shuffle.partitions=4
spark.default.parallelism=4
spark.executor.instances=1
spark.executor.cores=1
spark.executor.memory=512m
spark.driver.memory=512m
